import type { Metadata } from "next";
import {ReactNode} from 'react'
import localFont from "next/font/local";
import Header from '@/widgets--layout/Header'
import Footer from '@/widgets--layout/Footer'
import BackgroundImage from '@/shared--layout/BackgroundImage/BackgroundImage'
import layoutData from '@/data/layoutData.json'
import "./styles/globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      	<BackgroundImage 
      		mobile={layoutData.background.mobile}
      		desktop={layoutData.background.desktop}
      	/>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
